name: Azure Container Registry Build by MDP
branding:
  icon: truck
  color: red
author: Clark159
description: GitHub Action for Building Azure Container Registry

inputs:
  resourceGroupName:
    description: Resource Group Name
    required: true
    
  registryServerName:
    description: Registry Server Name
    required: true

  dockerImageName:
    description: Docker Image Name
    required: true

  dockerFilePath:
    description: Docker File Path
    required: true
    
runs:
  using: composite
  steps:
  
  - name: Configure Azure CLI
    uses: azure/CLI@v1
    with:
      inlineScript: |
        az configure --defaults location=$(az group show --name ${{ inputs.resourceGroupName }} --query location -o tsv)

  - name: Checkout GitHub Repository
    uses: actions/checkout@v4

  - name: Deploy Azure Container Registry
    uses: azure/CLI@v1
    with:
      inlineScript: |
         az acr build \
           --registry ${{ inputs.registryServerName }} \
           --file ${{ inputs.dockerFilePath }} \
           --image ${{ inputs.dockerImageName }}:${{ github.sha }} .          
