name: Deploy AzureContainerRegistry by MDP
branding:
  icon: truck
  color: red
author: Clark159
description: GitHub Action for Deploy AzureContainerRegistry


inputs:     
  resourceGroupName:
    description: ResourceGroup Name
    required: true

  containerAppsName:
    description: ContainerApps Name
    required: true

  dockerFilePath:
    description: DockerFile Path
    required: true

  containerRegistryName: 
    description: ContainerRegistry Name
    required: false


runs:
  using: composite
  steps:

    - name: Deploy ContainerRegistry
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.workflow }}-(${{ github.action }})-${{ github.run_number }}
        resourceGroupName: ${{ inputs.resourceGroupName }}
        template: ${{ github.action_path }}/main.bicep
        parameters: >-
           containerRegistryName=${{ inputs.containerRegistryName }}
        failOnStdErr: false
      id: arm-deploy

    - name: Deploy ContainerImage
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az acr build \
           --registry ${{ steps.arm-deploy.outputs.containerRegistryName }} \
           --file ${{ inputs.dockerFilePath }} \
           --image ${{ inputs.containerAppsName }}:${{ github.sha }} .

    - name: Display Outputs
      shell: bash
      run: |
        echo containerRegistryName=${{ steps.arm-deploy.outputs.containerRegistryName }}.azurecr.io
        echo containerImageName=${{ steps.arm-deploy.outputs.containerRegistryName }}.azurecr.io/${{ inputs.containerAppsName }}:${{ github.sha }}


outputs:
  containerRegistryName:
    description: ContainerRegistry Name
    value: ${{ steps.arm-deploy.outputs.containerRegistryName }}.azurecr.io

  containerImageName:
    description: ContainerImage Name
    value: ${{ steps.arm-deploy.outputs.containerRegistryName }}.azurecr.io/${{ inputs.containerAppsName }}:${{ github.sha }}