name: Deploy AzureContainerRegistry by MDP
branding:
  icon: truck
  color: red
author: Clark159
description: GitHub Action for Deploy AzureContainerRegistry


inputs:
  resourceGroupName:
    description: ResourceGroup Name
    required: true

  containerAppName:
    description: ContainerApp Name
    required: true

  dockerFilePath:
    description: DockerFile Path
    required: true
  
  deployHostPaths:
    description: DeployHost Paths
    required: false


runs:
  using: composite
  steps:
      
    - name: Check DeployType by MDP              
      uses: MDPOps/deploy-type-check@v1
      with:
        deployHostPaths: 
          ${{ inputs.deployHostPaths }}
      id: deploy-type-check

    - name: Deploy ContainerRegistry
      uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.workflow }}-(${{ github.action }})-${{ github.run_number }}
        resourceGroupName: ${{ inputs.resourceGroupName }}
        template: ${{ github.action_path }}/main.bicep
        failOnStdErr: false
      id: arm-deploy

    - name: Deploy DockerImage
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az acr build \
           --registry ${{ steps.arm-deploy.outputs.containerRegistryName }} \
           --file ${{ inputs.dockerFilePath }} \
           --image ${{ inputs.containerAppName }}:${{ github.sha }} .

    - name: Display Outputs
      shell: bash
      run: |
        echo deployType=${{ steps.deploy-type-check.outputs.deployType }}
        echo containerRegistryName=${{ steps.arm-deploy.outputs.containerRegistryName }}.azurecr.io
        echo containerImageName=${{ steps.arm-deploy.outputs.containerRegistryName }}.azurecr.io/${{ inputs.containerAppName }}:${{ github.sha }}


outputs:
  deployType:
    description: DeployType=[hosts/apps]
    value: ${{ steps.deploy-type-check.outputs.deployType }}

  containerRegistryName:
    description: ContainerRegistry Name
    value: ${{ steps.arm-deploy.outputs.containerRegistryName }}.azurecr.io

  containerImageName:
    description: containerImage Name
    value: ${{ steps.arm-deploy.outputs.containerRegistryName }}.azurecr.io/${{ inputs.containerAppName }}:${{ github.sha }}